# Generated by Django 5.2.15 on 2026-07-14 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagelog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='plan',
            name='price_egp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='campaigns_per_month',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='daily_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.transaction'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='campaigns_generated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='campaigns_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='daily_generation_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
