# Generated by Django 5.2.15 on 2026-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_usagelog_options_plan_price_egp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tx_ref',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
