# Generated by Django 5.2.15 on 2026-07-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_transaction_tx_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tx_ref',
        ),
    ]
