# Generated by Django 5.2.15 on 2026-08-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_remove_transaction_tx_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='price_egp',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price_zar',
        ),
    ]
