# Generated by Django 5.2.15 on 2026-09-13 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_remove_plan_price_egp_remove_plan_price_zar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='pricing_tra_flutter_6cf4ca_idx',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='flutterwave_ref',
            new_name='provider_reference',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['provider_reference'], name='pricing_tra_provide_50789c_idx'),
        ),
    ]
