# Generated by Django 5.2.15 on 2026-09-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_remove_transaction_pricing_tra_flutter_6cf4ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='payg_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
