# Generated by Django 5.2.15 on 2026-07-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('NG', 'Nigeria'), ('KE', 'Kenya'), ('GH', 'Ghana'), ('ZA', 'South Africa'), ('EG', 'Egypt'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
