# Generated by Django 5.2.15 on 2026-08-12 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PWAInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('os', models.CharField(db_index=True, max_length=32)),
                ('browser', models.CharField(max_length=32)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], db_index=True, max_length=16)),
                ('country', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('is_pwa', models.BooleanField(default=False, help_text="True once we've seen this device running standalone")),
                ('installed_at', models.DateTimeField(blank=True, help_text="First confirmed 'install' event", null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('lost_signal_at', models.DateTimeField(blank=True, help_text='Set when no heartbeat received for STALE_INSTALL_DAYS', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pwa_installations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PWAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('prompt_shown', 'Install prompt shown'), ('prompt_accepted', 'Install prompt accepted'), ('prompt_dismissed', 'Install prompt dismissed'), ('install', 'Installed'), ('session', 'Session heartbeat'), ('ios_instructions_shown', 'iOS instructions shown'), ('lost_signal', 'Lost install signal (system-generated)')], db_index=True, max_length=32)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pwa.pwainstallation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pwainstallation',
            index=models.Index(fields=['is_pwa', 'is_active'], name='pwa_pwainst_is_pwa_eff244_idx'),
        ),
        migrations.AddIndex(
            model_name='pwainstallation',
            index=models.Index(fields=['os', 'device_type'], name='pwa_pwainst_os_25b1ab_idx'),
        ),
        migrations.AddIndex(
            model_name='pwaevent',
            index=models.Index(fields=['event_type', 'created_at'], name='pwa_pwaeven_event_t_d211c1_idx'),
        ),
    ]
