# Generated by Django 5.2.15 on 2026-06-16 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('transparent_image', models.ImageField(blank=True, null=True, upload_to='transparent/')),
                ('flyer', models.ImageField(blank=True, null=True, upload_to='flyers/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('captions', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
