# Generated by Django 5.2.15 on 2026-06-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aijob',
            name='transparent_image',
        ),
    ]
