# Generated by Django 5.2.15 on 2026-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0002_remove_aijob_transparent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='stage',
            field=models.CharField(blank=True, default='pending', max_length=64),
        ),
    ]
