# Generated by Django 5.2.15 on 2026-06-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0003_aijob_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='image_nobg',
            field=models.ImageField(blank=True, null=True, upload_to='nobg/'),
        ),
    ]
