# Generated by Django 5.2.15 on 2026-06-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0004_aijob_image_nobg'),
    ]

    operations = [
        migrations.AddField(
            model_name='aijob',
            name='flyer_props',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
