# Generated by Django 5.2.15 on 2026-08-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0007_alter_aijob_video_previewrenderjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='previewrenderjob',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
